# Generated by Django 2.2.5 on 2019-09-24 11:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('live', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Hotel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hotelname', models.CharField(max_length=100)),
                ('hotellocation', models.CharField(max_length=100)),
                ('hoteladdress', models.TextField(max_length=300)),
                ('hotelstars', models.FloatField()),
            ],
        ),
    ]
