# Generated by Django 2.2.5 on 2019-09-25 08:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('live', '0002_hotel'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Hotel',
        ),
    ]
