# Generated by Django 2.2.5 on 2019-09-25 10:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('live', '0007_rooms'),
    ]

    operations = [
        migrations.CreateModel(
            name='Booking',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('checkin', models.DateField()),
                ('checkout', models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name='Room',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('room_type', models.IntegerField(choices=[(1, 'A/c double'), (2, 'A/c single'), (3, 'Non A/C Double'), (4, 'Non A/C single')], default=1)),
                ('room_pricing', models.IntegerField(default=0)),
                ('num_guests', models.IntegerField(choices=[(1, '2'), (2, '3')], default=1)),
                ('Amenities', models.CharField(max_length=100)),
            ],
        ),
        migrations.RenameField(
            model_name='hotel',
            old_name='hoteladdress',
            new_name='hotel_address',
        ),
        migrations.RenameField(
            model_name='hotel',
            old_name='hotelimage',
            new_name='hotel_image',
        ),
        migrations.RenameField(
            model_name='hotel',
            old_name='hotellocation',
            new_name='hotel_location',
        ),
        migrations.RenameField(
            model_name='hotel',
            old_name='hotelname',
            new_name='hotel_name',
        ),
        migrations.RenameField(
            model_name='hotel',
            old_name='hotelstars',
            new_name='hotel_stars',
        ),
        migrations.AlterField(
            model_name='profile',
            name='birthday',
            field=models.DateField(),
        ),
        migrations.DeleteModel(
            name='Rooms',
        ),
        migrations.AddField(
            model_name='room',
            name='hotel',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='live.Hotel'),
        ),
        migrations.AddField(
            model_name='booking',
            name='room',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='live.Room'),
        ),
    ]
