# Generated by Django 2.2.5 on 2019-09-26 05:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('live', '0009_profile_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hotel',
            name='hotel_image',
            field=models.ImageField(blank=True, height_field='100px', null=True, upload_to='', width_field='100px'),
        ),
    ]
