# Generated by Django 2.2.5 on 2019-09-26 08:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('live', '0012_room_room_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='room',
            name='room_name',
        ),
        migrations.AlterField(
            model_name='room',
            name='hotel',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='live.Hotel'),
        ),
    ]
