# Generated by Django 2.2.5 on 2019-09-26 09:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('live', '0013_auto_20190926_1350'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='birthday',
        ),
    ]
