# Generated by Django 2.2.5 on 2019-09-28 09:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('live', '0014_remove_profile_birthday'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='room',
            name='num_guests',
        ),
        migrations.AddField(
            model_name='booking',
            name='num_guests',
            field=models.IntegerField(choices=[(1, '2'), (2, '3')], default=1),
        ),
        migrations.AddField(
            model_name='room',
            name='max_guests',
            field=models.IntegerField(null=True),
        ),
    ]
