# Generated by Django 2.2.5 on 2019-09-28 10:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('live', '0017_booking_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='room',
            name='room_type',
            field=models.CharField(choices=[('A/c double', 'A/c double'), ('A/c single', 'A/c single'), ('Non A/C Double', 'Non A/C Double'), ('Non A/C single', 'Non A/C single')], default='A/c double', max_length=100),
        ),
    ]
