# Generated by Django 2.2.5 on 2019-09-28 11:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('live', '0018_auto_20190928_1629'),
    ]

    operations = [
        migrations.AlterField(
            model_name='room',
            name='room_type',
            field=models.IntegerField(choices=[(1, 'A/c double'), (2, 'A/c single'), (3, 'Non A/C Double'), (4, 'Non A/C single')], default=1),
        ),
    ]
